name: test

on:
  pull_request:
  push:
    branches:
      - "!gh-pages"
      - "**"
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]
        go: ["1.13", "1.14", "1.15"]
    name: ${{ matrix.os }} ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run test
        run: |
          go test ./...
        env:
          CVR_DEV_TEST_API_KEY: ${{ secrets.CVR_DEV_TEST_API_KEY }}
